[tool.poetry]
name = "beaver-habits"
version = "0.1.0"
description = ""
authors = ["Chanjian Zhu <daya0576@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
nicegui = "^1.4.18"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
